ITEM_MAPPING = {
    --Items
    [35000] = {}, -- compass
    [35001] = {"lighttank", "toggle"}, -- lightweight high capacity tank
    [35002] = {"console", "toggle"}, -- vehicle upgrade console
    [35003] = {"ultrafins", "toggle"}, -- ultra glide fins
    [35004] = {}, -- cyclops sonar module
    [35005] = {"armor", "toggle"}, -- reinforced dive suit
    [35006] = {}, -- cyclops thermal reactor module
    [35007] = {}, -- stillsuit
    [35008] = {"containment", "toggle"}, -- alien containment
    [35009] = {}, -- creature decoy
    [35010] = {}, -- cyclops fire suppression system
    [35011] = {}, -- swim charge fins
    [35012] = {"repcannon", "toggle"}, -- repulsion cannon
    [35013] = {}, -- cyclops decoy tube upgrade
    [35014] = {"shield", "toggle"}, -- cyclops shield generator 
    [35015] = {"cd1", "toggle"}, -- cyclops depth module mk1
    [35016] = {}, -- cyclops docking bay repair module
    [35017] = {}, -- battery charger fragment
    [35018] = {}, -- beacon fragment
    [35019] = {}, -- bioreactor fragment
    [35020] = {"cyclopsbridge", "consumable"}, -- cyclops bridge fragment
    [35021] = {"cyclopsengine", "consumable"}, -- cyclops engine fragment
    [35022] = {"cyclopshull", "consumable"}, -- cyclops hull fragment
    [35023] = {}, -- grav Trap Fragment
    [35024] = {"cutter", "consumable"}, -- laser cutter fragment
    [35025] = {}, -- light stick fragment
    [35026] = {"vehiclebay", "consumable"},
    [35027] = {"modify", "consumable"},
    [35028] = {"moonpool", "consumable"},
    [35029] = {}, -- nuclear reactor fragment
    [35030] = {}, -- power cell charger fragment
    [35031] = {}, -- power transmitter fragment
    [35032] = {"prawn", "consumable"}, -- prawn suit fragment
    [35033] = {}, -- prawn drill arm
    [35034] = {"grapple", "consumable"}, -- prawn grappling arm
    [35035] = {"prawnprop", "consumable"}, -- prawn propulsion cannon
    [35036] = {}, -- prawn torpedo arm
    [35037] = {}, -- scanner room fragment
    [35038] = {"seamoth", "consumable"}, -- seamoth
    [35039] = {"stasis", "consumable"}, -- stasis rifle
    [35040] = {}, -- thermal plant
    [35041] = {"seaglide", "consumable"}, -- seaglide
    [35042] = {"radsuit", "toggle"}, -- radiation suit 
    [35043] = {"propcannon", "consumable"}, -- propulsion cannon
    [35044] = {"base", "toggle"}, -- neptune launch platform
    [35045] = {"ionpower", "toggle"}, -- ion power cell
    [35046] = {}, -- exterior growbed
    [35047] = {}, -- picture frame
    [35048] = {}, -- bench fragment
    [35049] = {}, -- basic plant pot
    [35050] = {}, -- interior growbed
    [35051] = {}, -- plant shelf
    [35052] = {}, -- observatory
    [35053] = {"multipurpose", "toggle"}, -- multipurpose room
    [35054] = {}, -- bulkhead
    [35055] = {}, -- spotlight
    [35056] = {}, -- desk
    [35057] = {}, -- swivel chair
    [35058] = {}, -- office chair
    [35059] = {}, -- command chair
    [35060] = {}, -- counter
    [35061] = {}, -- single bed
    [35062] = {}, -- basic double bed
    [35063] = {}, -- quilted double bed
    [35064] = {}, -- coffee vending machine
    [35065] = {}, -- trash can
    [35066] = {}, -- floodlight
    [35067] = {}, -- bar table
    [35068] = {}, -- vending machine
    [35069] = {}, -- single wall shelf
    [35070] = {}, -- wall shelves
    [35071] = {}, -- round plant pot
    [35072] = {}, -- chic plant pot
    [35073] = {}, -- nuclear waste disposal
    [35074] = {}, -- wall planter
    [35075] = {"ionbattery", "toggle"}, -- ion battery
    [35076] = {"gantry", "toggle"}, -- neptune gantry
    [35077] = {"boosters", "toggle"}, -- neptune boosters
    [35078] = {"reserves", "toggle"}, -- neptune fuel reserve
    [35079] = {"cockpit", "toggle"}, -- neptune cockpit
    [35080] = {}, -- water filtration machine
    [35081] = {"ultratank", "toggle"}, -- ultra high capacity tank
    [35082] = {"largeroom", "toggle"}, -- large room
    [35083] = {}, -- large room glass dome
    [35084] = {}, -- multipurpose room glass dome
    [35085] = {}, -- partition
    [35086] = {}, -- partition door
    [35100] = {}, -- furniture
    [35101] = {} -- farming
}
SETTING_MAPPING = {
    ["goal"] = "goal",
    ["swim_rule"] = "swimrule",
    ["vanilla_tech"] = "pooltype",
    ["death_link"] = "deathlink",
    ["free_samples"] = "samples",
    ["creatures_to_scan"] = ""
}
CREATURE_MAPPING = {
    ["Amoeboid"] = "Amoeboid badge",
    ["Ancient Floater"] = "Ancient Floater badge",
    ["Bladderfish"] = "Bladderfish badge",
    ["Boomerang"] = "Boomerang badge",
    ["Crimson Ray"] = "Crimson Ray badge",
    ["Eyeye"] = "Eyeye badge",
    ["Floater"] = "Floater badge",
    ["Garryfish"] = "Garryfish badge",
    ["Gasopod"] = "Gasopod badge",
    ["Ghostray"] = "Ghostray badge",
    ["Holefish"] = "Holefish badge",
    ["Hoopfish"] = "Hoopfish badge",
    ["Hoverfish"] = "Hoverfish badge",
    ["Jellyray"] = "Jellyray badge",
    ["Lava Larva"] = "Lava Larva badge",
    ["Magmarang"] = "Magmarang badge",
    ["Oculus"] = "Oculus badge",
    ["Peeper"] = "Peeper badge",
    ["Rabbit Ray"] = "Rabbit Ray badge",
    ["Red Eyeye"] = "Red Eyeye badge",
    ["Reefback Leviathan"] = "Reefback Leviathan badge",
    ["Reginald"] = "Reginald badge",
    ["Rockgrub"] = "Rockgrub badge",
    ["Sea Emperor Juvenile"] = "Sea Emperor Juvenile badge",
    ["Sea Treader Leviathan"] = "Sea Treader Leviathan badge",
    ["Shuttlebug"] = "Shuttlebug badge",
    ["Skyray"] = "Skyray badge",
    ["Spadefish"] = "Spadefish badge",
    ["Spinefish"] = "Spinefish badge",
    ["Biter"] = "Biter badge",
    ["Bleeder"] = "Bleeder badge",
    ["Blighter"] = "Blighter badge",
    ["Blood Crawler"] = "Blood Crawler badge",
    ["Cave Crawler"] = "Cave Crawler badge",
    ["Ghost Leviathan Juvenile"] = "Ghost Leviathan Juvenile badge",
    ["Ghost Leviathan"] = "Ghost Leviathan badge",
    ["Reaper Leviathan"] = "Reaper Leviathan badge",
    ["River Prowler"] = "River Prowler badge",
    ["Sea Dragon Leviathan"] = "Sea Dragon Leviathan badge",
    ["Warper"] = "Warper badge",
    ["Ampeel"] = "Ampeel badge",
    ["Boneshark"] = "Boneshark badge",
    ["Crabsquid"] = "Crabsquid badge",
    ["Crabsnake"] = "Crabsnake badge",
    ["Crashfish"] = "Crashfish badge",
    ["Lava Lizard"] = "Lava Lizard badge",
    ["Mesmer"] = "Mesmer badge",
    ["Sand Shark"] = "Sand Shark badge",
    ["Stalker"] = "Stalker badge",
    ["Cuddlefish"] = "Cuddlefish badge"
}