LOCATION_MAPPING = {
    [33000] = {"@Crater/Blood Kelp Trench Wreck\n350m below/Outside Databox"},
    [33001] = {"@Crater/Blood Kelp Trench Wreck\n350m below/Inside Databox"},
    [33002] = {"@Crater/Blood Kelp Trench Wreck\n350m below/PDA"},
    [33003] = {"@Crater/Bulb Zone West Wreck\n220m below/Outside Databox"},
    [33004] = {"@Crater/Bulb Zone West Wreck\n220m below/Under Databox"},
    [33005] = {"@Crater/Bulb Zone West Wreck\n220m below/Inside Databox"},
    [33006] = {"@Crater/Bulb Zone West Wreck\n220m below/PDA"},
    [33007] = {"@Crater/Bulb Zone East Wreck\n235m below/Databox"},
    [33008] = {"@Crater/Dunes North Wreck\n345m below/Outside Databox"},
    [33009] = {"@Crater/Dunes North Wreck\n345m below/Office Databox"},
    [33010] = {"@Crater/Dunes North Wreck\n345m below/PDA"},
    [33011] = {"@Crater/Dunes North Wreck\n345m below/Cargo Databox"},
    [33012] = {"@Crater/Dunes West Wreck\n360m below/Databox"},
    [33013] = {"@Crater/Dunes East Wreck\n225m below/Outside Databox"},
    [33014] = {"@Crater/Dunes East Wreck\n225m below/Inside Databox"},
    [33015] = {"@Crater/Grand Reef North Wreck\n265m below/Outside Databox"},
    [33016] = {"@Crater/Grand Reef North Wreck\n265m below/Elevator Databox"},
    [33017] = {"@Crater/Grand Reef North Wreck\n265m below/Bottom Databox"},
    [33018] = {"@Crater/Grand Reef North Wreck\n265m below/Hangar PDA"},
    [33019] = {"@Crater/Grand Reef South Wreck\n475m below/Trench Databox"},
    [33020] = {"@Crater/Grand Reef South Wreck\n475m below/Comms Databox"},
    [33021] = {"@Crater/Grand Reef South Wreck\n475m below/Outside Databox"},
    [33022] = {"@Crater/Grand Reef South Wreck\n475m below/PDA"},
    [33023] = {"@Crater/Grassy Plateaus South Wreck\n110m below/Databox"},
    [33024] = {"@Crater/Grassy Plateaus South Wreck\n110m below/PDA"},
    [33025] = {"@Crater/Grassy Plateaus East Wreck\n105m below/Breach Databox"},
    [33026] = {"@Crater/Grassy Plateaus East Wreck\n105m below/Hangar Databox"},
    [33027] = {"@Crater/Grassy Plateaus West Wreck\n110m below/Locker PDA"},
    [33028] = {"@Crater/Grassy Plateaus West Wreck\n110m below/Data Terminal"},
    [33029] = {"@Crater/Grassy Plateaus Southwest Wreck\n110m below/Databox"},
    [33030] = {"@Crater/Safe Shallows Wreck\n30m below/PDA"},
    [33031] = {"@Crater/Kelp Forest West Wreck\n80m below/Databox"},
    [33032] = {"@Crater/Kelp Forest North Wreck\n40m below/PDA"},
    [33033] = {"@Crater/Mountains West Wreck\n390m below/Outside Databox"},
    [33034] = {"@Crater/Mountains West Wreck\n390m below/Data Terminal"},
    [33035] = {"@Crater/Mountains West Wreck\n390m below/Hangar Databox"},
    [33036] = {"@Crater/Mountains West Wreck\n390m below/Office Databox"},
    [33037] = {"@Crater/Mountains East Wreck\n290m below/Comms Databox"},
    [33038] = {"@Crater/Mountains East Wreck\n290m below/Outside Databox"},
    [33039] = {"@Crater/Northwestern Mushroom Forest Wreck\n115m below/Cargo Databox"},
    [33040] = {"@Crater/Northwestern Mushroom Forest Wreck\n115m below/Office Databox"},
    [33041] = {"@Crater/Northwestern Mushroom Forest Wreck\n115m below/PDA"},
    [33042] = {"@Crater/Sea Treader's Path Wreck\n195m below/Outside Databox"},
    [33043] = {"@Crater/Sea Treader's Path Wreck\n195m below/Hangar Databox"},
    [33044] = {"@Crater/Sea Treader's Path Wreck\n195m below/Lobby Databox"},
    [33045] = {"@Crater/Sea Treader's Path Wreck\n195m below/PDA"},
    [33046] = {"@Crater/Sparse Reef Wreck\n215m below/Locker Databox"},
    [33047] = {"@Crater/Sparse Reef Wreck\n215m below/Outside Databox"},
    [33048] = {"@Crater/Sparse Reef Wreck\n215m below/Lab Databox"},
    [33049] = {"@Crater/Underwater Islands Wreck\n200m below/Outside Databox"},
    [33050] = {"@Crater/Underwater Islands Wreck\n200m below/Hangar Databox"},
    [33051] = {"@Crater/Underwater Islands Wreck\n200m below/Data Terminal"},
    [33052] = {"@Crater/Underwater Islands Wreck\n200m below/Cable Databox"},
    [33053] = {"@Crater/Underwater Islands Wreck\n200m below/Pipes Databox 1"},
    [33054] = {"@Crater/Underwater Islands Wreck\n200m below/Pipes Databox 2"},
    [33055] = {"@Crater/Deep Grand Reef Degasi Seabase\n510m below/Bedroom Databox"},
    [33056] = {"@Crater/Deep Grand Reef Degasi Seabase\n510m below/Observatory Databox"},
    [33057] = {"@Crater/Deep Grand Reef Degasi Seabase\n510m below/Bedroom PDA"},
    [33058] = {"@Crater/Deep Grand Reef Degasi Seabase\n510m below/Outside PDA"},
    [33059] = {"@Crater/Deep Grand Reef Degasi Seabase\n510m below/Observatory PDA"},
    [33060] = {"@Crater/Deep Grand Reef Degasi Seabase\n510m below/Lab PDA"},
    [33061] = {"@Crater/Floating Island\nSurface/Lake - PDA"},
    [33062] = {"@Crater/Floating Island\nSurface/Central Base - Databox"},
    [33063] = {"@Crater/Floating Island\nSurface/Central Base - Room PDA"},
    [33064] = {"@Crater/Floating Island\nSurface/Central Base - Green Wall PDA"},
    [33065] = {"@Crater/Floating Island\nSurface/Central Base - Corridor PDA"},
    [33066] = {"@Crater/Floating Island\nSurface/North Observatory - PDA"},
    [33067] = {"@Crater/Floating Island\nSurface/South Observatory - PDA"},
    [33068] = {"@Cave Networks/Jellyshroom Cave\n250m below/PDA"},
    [33069] = {"@Cave Networks/Jellyshroom Degasi Seabase\n275m below/Bedroom Databox"},
    [33070] = {"@Cave Networks/Jellyshroom Degasi Seabase\n275m below/Detached PDA"},
    [33071] = {"@Cave Networks/Jellyshroom Degasi Seabase\n275m below/Office PDA"},
    [33072] = {"@Cave Networks/Jellyshroom Degasi Seabase\n275m below/Locker PDA"},
    [33073] = {"@Cave Networks/Jellyshroom Degasi Seabase\n275m below/Bedroom PDA"},
    [33074] = {"@Cave Networks/Jellyshroom Degasi Seabase\n275m below/Observatory PDA"},
    [33075] = {"@Crater/Lifepod 2\n505m below/Databox"},
    [33076] = {"@Crater/Lifepod 2\n505m below/PDA"},
    [33077] = {"@Crater/Lifepod 3\n25m below/Databox"},
    [33078] = {"@Crater/Lifepod 3\n25m below/PDA"},
    [33079] = {"@Crater/Lifepod 4\nSurface/Databox"},
    [33080] = {"@Crater/Lifepod 4\nSurface/PDA"},
    [33081] = {"@Crater/Lifepod 6\n120m below/Databox"},
    [33082] = {"@Crater/Lifepod 6\n120m below/Inside PDA"},
    [33083] = {"@Crater/Lifepod 6\n120m below/Outside PDA"},
    [33084] = {"@Crater/Lifepod 7\n185m below/PDA"},
    [33085] = {"@Crater/Lifepod 12\n275m below/Databox"},
    [33086] = {"@Crater/Lifepod 12\n275m below/PDA"},
    [33087] = {"@Crater/Lifepod 13\n185m below/Databox"},
    [33088] = {"@Crater/Lifepod 13\n185m below/PDA"},
    [33089] = {"@Crater/Lifepod 17\n100m below/PDA"},
    [33090] = {"@Crater/Lifepod 19\n305m below/Databox"},
    [33091] = {"@Crater/Lifepod 19\n305m below/Outside PDA"},
    [33092] = {"@Crater/Lifepod 19\n305m below/Inside PDA"},
    [33093] = {"@Crater/Upper Aurora/Seamoth Bay - Upgrade Console"},
    [33094] = {"@Crater/Upper Aurora/Drive Room - Upgrade Console"},
    [33095] = {"@Crater/Lower Aurora/Prawn Bay - Upgrade Console"},
    [33096] = {"@Crater/Upper Aurora/Office - PDA"},
    [33097] = {"@Crater/Upper Aurora/Entrance - PDA"},
    [33098] = {"@Crater/Upper Aurora/Cargo Bay - PDA\n(Code 1454)"},
    [33099] = {"@Crater/Upper Aurora/Seamoth Bay - PDA"},
    [33100] = {"@Crater/Lower Aurora/Locker Room - Medkit Locker PDA"},
    [33101] = {"@Crater/Lower Aurora/Locker Room - Locker Floor PDA"},
    [33102] = {"@Crater/Aurora Crew Quarters/Cafeteria PDA"},
    [33103] = {"@Crater/Aurora Crew Quarters/Cabin 4 PDA"},
    [33104] = {"@Crater/Aurora Crew Quarters/Cabin 7 PDA"},
    [33105] = {"@Crater/Aurora Crew Quarters/Cabin 1 PDA\n(Code 1869)"},
    [33106] = {"@Crater/Aurora Crew Quarters/Captain's Quarters PDA\n(Code 2679)"},
    [33107] = {"@Crater/Lower Aurora/Ring - PDA"},
    [33108] = {"@Crater/Lower Aurora/Lab - PDA\n(Code 6483)"},
    [33109] = {"@Crater/Upper Aurora/Office - Data Terminal"}, -- location: "Aurora - Office Data Terminal". Not in tracker?
    [33110] = {"@Crater/Aurora Crew Quarters/Captain's Quarters Data Terminal\n(Code 2679)"},
    [33111] = {"@Crater/Lower Aurora/Black Box - Data Terminal"},
    [33112] = {"@Crater/Lower Aurora/Lab - Data Terminal\n(Code 6483)"},
    [33113] = {"@Crater/Quarantine Enforcement Platform\nSurface/Upper Alien Data Terminal"},
    [33114] = {"@Crater/Quarantine Enforcement Platform\nSurface/Center Alien Data Terminal"},
    [33115] = {"@Crater/Dunes Sanctuary (Requires Purple Tablet)\n400m below/Alien Data Terminal"},
    [33116] = {"@Crater/Sparse Reef Sanctuary (Requires Purple Tablet)\n315m below/Alien Data Terminal"},
    [33117] = {"@Crater/North Blood Kelp Sanctuary (Requires Purple Tablet)\n565m below/Alien Data Terminal"},
    [33118] = {"@Cave Networks/Lost River Laboratory Cache (requires orange tablet)\n690m below/Alien Data Terminal"},
    [33119] = {"@Cave Networks/Disease Research Facility\n815m below/Upper Alien Data Terminal\n(Requires Purple Tablet)"},
    [33120] = {"@Cave Networks/Disease Research Facility\n815m below/Center Alien Data Terminal"},
    [33121] = {"@Cave Networks/Disease Research Facility\n815m below/Lower Alien Data Terminal"},
    [33122] = {"@Cave Networks/Alien Thermal Plant\n1230m below/Entrance Alien Data Terminal"},
    [33123] = {"@Cave Networks/Alien Thermal Plant\n1230m below/Lower Alien Data Terminal"},
    [33124] = {"@Cave Networks/Alien Thermal Plant\n1230m below/Upper Alien Data Terminal"},
    [33125] = {"@Cave Networks/Primary Containment Facility (Requires Blue Tablet)\n1445m below/Central Room - Alien Data Terminal"},
    [33126] = {"@Cave Networks/Primary Containment Facility (Requires Blue Tablet)\n1445m below/Egg Laboratory - Alien Data Terminal"},
    [33127] = {"@Cave Networks/Primary Containment Facility (Requires Blue Tablet)\n1445m below/Pipe Room - Alien Data Terminal"},
    [33128] = {"@Crater/Grassy Plateaus West Wreck\n110m below/Beam PDA"},
    [33129] = {"@Crater/Floating Island\nSurface/Cave Entrance - PDA"},
    [33130] = {"@Cave Networks/Jellyshroom Degasi Seabase\n275m below/Outside PDA"},

    --Creatures
    [34000] = {"Gasopod", "toggle"}, -- Gasopod
    [34001] = {"Bladderfish", "toggle"}, -- Bladderfish
    [34002] = {"Ancient Floater", "toggle"}, -- Ancient Floater
    [34003] = {"Skyray", "toggle"}, -- Skyray
    [34004] = {"Garryfish", "toggle"}, -- Garryfish
    [34005] = {"Peeper", "toggle"}, -- Peeper
    [34006] = {"Shuttlebug", "toggle"}, -- Shuttlebug
    [34007] = {"Rabbit Ray", "toggle"}, -- Rabbit Ray
    [34008] = {"Stalker", "toggle"}, -- Stalker/Doggo
    [34009] = {"Floater", "toggle"}, -- Floater
    [34010] = {"Holefish", "toggle"}, -- Holefish
    [34011] = {"Cave Crawler", "toggle"}, -- Cave Crawler/Crab
    [34012] = {"Hoopfish", "toggle"}, -- Hoopfish
    [34013] = {"Crashfish", "toggle"}, -- Crashfish
    [34014] = {"Hoverfish", "toggle"}, -- Hoverfish
    [34015] = {"Spadefish", "toggle"}, -- Spadefish
    [34016] = {"Reefback Leviathan", "toggle"}, -- Reefback
    [34017] = {"Reaper Leviathan", "toggle"}, -- Reaper Leviathan
    [34018] = {"Warper", "toggle"}, -- Warper
    [34019] = {"Boomerang", "toggle"}, -- Boomerang
    [34020] = {"Biter", "toggle"}, -- Biter
    [34021] = {"Sand Shark", "toggle"},  -- Sand Shark
    [34022] = {"Bleeder", "toggle"}, -- Bleeder
    [34023] = {"Crabsnake", "toggle"}, -- Crabsnake
    [34024] = {"Jellyray", "toggle"}, -- Jellyray
    [34025] = {"Oculus", "toggle"}, -- Oculus
    [34026] = {"Mesmer", "toggle"}, -- Mesmer
    [34027] = {"Eyeye", "toggle"}, -- Eyeye
    [34028] = {"Reginald", "toggle"}, -- Reginald
    [34029] = {"Sea Treader Leviathan", "toggle"}, -- Sea Treader
    [34030] = {"Crabsquid", "toggle"}, -- Crabsquid
    [34031] = {"Ampeel", "toggle"}, -- Ampeel
    [34032] = {"Boneshark", "toggle"}, -- Boneshark
    [34033] = {"Rockgrub", "toggle"}, -- Rockgrub
    [34034] = {"Ghost Leviathan", "toggle"}, -- Adult Ghost Leviathan
    [34035] = {"Ghost Leviathan Juvenile", "toggle"}, -- Juvenile Ghost Leviathan
    [34036] = {"Spinefish", "toggle"}, -- Spinefish
    [34037] = {"Blighter", "toggle"},  -- Blighter
    [34038] = {"Blood Crawler", "toggle"}, -- Blood Crawler
    [34039] = {"Ghostray", "toggle"}, -- Ghostray
    [34040] = {"Amoeboid", "toggle"}, --Amoeboid
    [34041] = {"River Prowler", "toggle"}, -- River Prowler
    [34042] = {"Red Eyeye", "toggle"}, -- Red Eyeye
    [34043] = {"Magmarang", "toggle"}, -- Magmarang
    [34044] = {"Crimson Ray", "toggle"}, -- Crimson Ray
    [34045] = {"Lava Larva", "toggle"}, -- Lava Larva
    [34046] = {"Lava Lizard", "toggle"}, -- Lava Lizard
    [34047] = {"Sea Dragon Leviathan", "toggle"}, -- Sea Dragon Leviathan
    [34048] = {"Cuddlefish", "toggle"}, -- Cuddlefish
    [34049] = {"Sea Emperor Juvenile", "toggle"} -- Sea Emperor Baby
}
